- name: Create configuration directory
  win_file:
    path: "{{ sysmon_config_path }}"
    state: directory

- name: Check if sysmon is installed
  win_service:
    name: sysmon
  register: sysmon_installed
  ignore_errors: yes
  when: ansible_architecture2 == "x86_32"

- name: Check if sysmon64 is installed
  win_service:
    name: sysmon64
  register: sysmon64_installed
  ignore_errors: yes
  when: ansible_architecture2 == "x86_64"

- name: Check sysmon version
  win_file_version:
    path: "{{ sysmon_install_path }}\\Sysmon.exe"
  ignore_errors: yes
  register: sysmon_installed_version
  when:
    - ansible_architecture2 == "x86_32"
    - sysmon_installed.exists

- name: Check sysmon64 version
  win_file_version:
    path: "{{ sysmon_install_path }}\\Sysmon64.exe"
  ignore_errors: yes
  register: sysmon64_installed_version
  when:
    - ansible_architecture2 == "x86_64"
    - sysmon64_installed.exists

#- debug: var=sysmon64_installed_version

# Uninstall Sysmon only if lower than version specified in sysmon_version variable.
- name: Uninstall sysmon
  win_command: sysmon -u
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture2 == "x86_32"
    - sysmon_installed.exists
    - sysmon_installed_version.failed or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: Uninstall sysmon64
  win_command: sysmon64 -u
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture2 == "x86_64"
    - sysmon64_installed.exists
    - sysmon64_installed_version.failed or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

#- name: Download Sysmon
#  win_get_url:
#    url: "https://download.sysinternals.com/files/Sysmon.zip"
#    dest: "{{ sysmon_install_path }}\\Sysmon.zip"
#  when:
#    - ansible_architecture2 == "x86_32"
#    - not sysmon_installed.exists or sysmon_installed_version.failed or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: upload Sysmon.zip x86
  win_copy:
    src: files/Sysmon.zip
    dest: "{{ sysmon_install_path }}\\Sysmon.zip"
  when:
    - ansible_architecture2 == "x86_32"
    - not sysmon_installed.exists or sysmon_installed_version.failed or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: Unzip Sysmon
  win_unzip:
    src: "{{ sysmon_install_path }}\\Sysmon.zip"
    dest: "{{ sysmon_install_path }}\\"
    delete_archive: yes
  when:
    - ansible_architecture2 == "x86_32"
    - not sysmon_installed.exists or sysmon_installed_version.failed or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

#- name: Download Sysmon64
#  win_get_url:
#    url: "https://download.sysinternals.com/files/Sysmon.zip"
#    dest: "{{ sysmon_install_path }}\\Sysmon.zip"
#  when:
#    - ansible_architecture2 == "x86_64"
#    - not sysmon64_installed.exists or sysmon64_installed_version.failed or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: upload Sysmon.zip x64
  win_copy:
    src: files/Sysmon.zip
    dest: "{{ sysmon_install_path }}\\Sysmon.zip"
  when:
    - ansible_architecture2 == "x86_64"
    - not sysmon64_installed.exists or sysmon64_installed_version.failed or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: Unzip Sysmon64
  win_unzip:
    src: "{{ sysmon_install_path }}\\Sysmon.zip"
    dest: "{{ sysmon_install_path }}\\"
    delete_archive: yes
  when:
    - ansible_architecture2 == "x86_64"
    - not sysmon64_installed.exists or sysmon64_installed_version.failed or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204

- name: Install sysmon
  win_command: sysmon -i -accepteula
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture2 == "x86_32"
    - not sysmon_installed.exists or sysmon_installed_version.failed or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204
  notify: restart-sysmon

- name: Install sysmon64
  win_command: sysmon64 -i -accepteula
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture2 == "x86_64"
    - not sysmon64_installed.exists or sysmon64_installed_version.failed or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<') # noqa 204
  #notify: restart-sysmon64

- name: Upload sysmon configuration
  win_copy:
    src: files/{{ sysmon_config }}
    dest: "{{ sysmon_config_path }}\\sysmonconfig-export.xml"
  notify: reload-sysmon
  when: ansible_architecture2 == "x86_32"
  tags: configure

- name: Upload sysmon64 configuration
  win_copy:
    src: files/{{ sysmon_config }}
    dest: "{{ sysmon_config_path }}\\sysmonconfig-export.xml"
  notify: reload-sysmon64
  when: ansible_architecture2 == "x86_64"
  tags: configure
